-------------------------미타씨 파트--------------------------------
CREATE TABLE MEMBER ( -- 회원 테이블
    MEM_NO VARCHAR2(50) CONSTRAINT PK_MEM_NO PRIMARY KEY -- 회원 번호(PK)
    , MEM_PW VARCHAR2(50) NOT NULL -- 회원 비밀번호
    , MEM_NAME VARCHAR2(10 CHAR) NOT NULL -- 회원 이름
    , MEM_EMAIL VARCHAR2(100) CONSTRAINT UK_MEM_EMAIL UNIQUE NOT NULL -- 회원 이메일
    , MEM_ADDR VARCHAR2(100 CHAR) NOT NULL -- 회원 주소
    , MEM_PHONE VARCHAR2(30) CONSTRAINT UK_MEM_PHONE UNIQUE NOT NULL -- 회원 연락처
    , MEM_IMAGE VARCHAR2(100 CHAR) NOT NULL -- 회원 사진
    , MEM_GENDER VARCHAR2(10) NOT NULL -- 회원 성별
    , MEM_BIRTH DATE NOT NULL -- 회원 생일
    , MEM_TYPE VARCHAR2(10) NOT NULL -- 회원 유형
    , IS_JOIN VARCHAR2(10) DEFAULT 'Y' NOT NULL -- 가입/탈퇴 여부
    , CREATE_DATE DATE DEFAULT SYSDATE NOT NULL -- 회원 가입일
    , WITHDRAW_DATE DATE -- 회원 탈퇴일
);

CREATE TABLE BOARD_CATEGORY ( -- 게시판 카테고리 테이블
    CATE_NO VARCHAR2(50) CONSTRAINT PK_CATE_NO PRIMARY KEY -- 카테고리 번호(PK)
    , CATE_NAME VARCHAR2(30 CHAR) CONSTRAINT UK_CATE_NAME UNIQUE NOT NULL -- 카테고리명
);

CREATE TABLE BOARD ( -- 게시판 테이블
    BOARD_NO VARCHAR2(50) CONSTRAINT PK_BOARD_NO PRIMARY KEY -- 게시판 번호(PK)
    , BOARD_TITLE VARCHAR2(100 CHAR) NOT NULL -- 게시판 제목
    , BOARD_CONTENT VARCHAR2(1000 CHAR) -- 게시판 내용
    , CREATE_DATE DATE DEFAULT SYSDATE NOT NULL -- 게시판 작성일
    , UPDATE_DATE DATE -- 게시판 마지막 수정일
    , IS_DELETE VARCHAR2(10) DEFAULT 'N' NOT NULL -- 게시판 삭제 여부
    , READ_CNT NUMBER DEFAULT 0 NOT NULL -- 게시판 조회 수
    , REPLY_CNT NUMBER DEFAULT 0 NOT NULL -- 게시판 댓글 수
    , CATE_NO VARCHAR2(50) CONSTRAINT FK_BOARD_CATE_NO REFERENCES BOARD_CATEGORY (CATE_NO) NOT NULL -- 게시판 카테고리(FK)
);

CREATE TABLE REPLY ( -- 댓글 테이블
    REPLY_NO VARCHAR2(50) CONSTRAINT PK_REPLY_NO PRIMARY KEY -- 댓글 번호(PK)
    , BOARD_NO VARCHAR2(50) CONSTRAINT FK_REPLY_BOARD_NO REFERENCES BOARD (BOARD_NO) ON DELETE CASCADE NOT NULL -- 게시글 번호(FK)
    , REPLY_CONTENT VARCHAR2(100 CHAR) NOT NULL -- 댓글 내용
    , REPLY_WRITER VARCHAR2(50) CONSTRAINT FK_REPLY_WRITER REFERENCES MEMBER (MEM_NO) ON DELETE CASCADE NOT NULL -- 댓글 작성자
    , CREATE_DATE DATE DEFAULT SYSDATE NOT NULL -- 댓글 작성일
    , UPDATE_DATE DATE -- 댓글 마지막 수정일
);

CREATE TABLE COLLEGE ( -- 단과대학 테이블
    COLL_NO VARCHAR2(50) CONSTRAINT PK_COLL_NO PRIMARY KEY -- 단과대학 번호(PK)
    , COLL_NAME VARCHAR2(20 CHAR) CONSTRAINT UK_COLL_NAME UNIQUE NOT NULL -- 단과대학명
);

CREATE TABLE DEPT ( -- 학과 테이블
    DEPT_NO VARCHAR2(50) CONSTRAINT PK_DEPT_NO PRIMARY KEY -- 학과 번호(PK)
    , DEPT_NAME VARCHAR2(20 CHAR) CONSTRAINT UK_DEPT_NAME UNIQUE NOT NULL -- 학과명
    , COLL_NO VARCHAR2(50) CONSTRAINT FK_DEPT_COLL_NO REFERENCES COLLEGE (COLL_NO) ON DELETE CASCADE NOT NULL -- 단과대학 번호(FK)
);

CREATE TABLE STUDENT ( -- 임시 학생 테이블
    STU_NO VARCHAR2(50) PRIMARY KEY
    , MEM_NO VARCHAR2(50) REFERENCES MEMBER (MEM_NO) NOT NULL
);
--------------------------내 파트--------------------------------
CREATE TABLE EMP ( -- 직원 테이블
	EMP_NO VARCHAR2(50) PRIMARY KEY
	, EMP_TYPE VARCHAR2(50)	NOT NULL
	, EMP_JOB VARCHAR2(50)	NOT NULL
	, MEM_NO VARCHAR2(50)	NOT NULL
	, DEPT_NO VARCHAR2(50)	REFERENCES COLLEGE (COLL_NO)
	, COLL_NO VARCHAR2(50)	REFERENCES DEPT (DEPT_NO)
);
--------------------------강국씨 파트---------------------------
--강의 등록 테이블
CREATE TABLE LEC (
    LEC_NO VARCHAR2(100) PRIMARY KEY --강의 PK     LEC_1, LEC_2.....
    , LEC_NAME VARCHAR2(200) NOT NULL --강의 이름
    , LEC_SCORE NUMBER NOT NULL --강의 학점
    , COLL_NO VARCHAR2(50) NOT NULL REFERENCES COLLEGE(COLL_NO) --단대 번호 FK
    , DEPT_NO VARCHAR2(50) NOT NULL REFERENCES DEPT(DEPT_NO) -- 소속 학과 FK
    , LEC_PR VARCHAR2(100) NOT NULL --담당 교수
    , CREATE_DATE VARCHAR2(100) DEFAULT SYSDATE 
    , MAX_NUM VARCHAR2(100) NOT NULL --최대 인원
    , NOW_NUM VARCHAR2(100) DEFAULT 0 --현재 인원
    , LEC_DATE VARCHAR2(200) NOT NULL --강의 날짜 및 시간
    , LEC_MEMO VARCHAR2(100) --강의 메모
);

-- 성적 등록 테이블
CREATE TABLE STU_SCORE (
    LEC_NO VARCHAR2(100) PRIMARY KEY REFERENCES LEC(LEC_NO)  --강의 PK
    , GRADE VARCHAR2(100) NOT NULL --성적
    , STU_NO VARCHAR2(100) NOT NULL REFERENCES STUDENT(STU_NO) --학생 번호
    , SEM_NO VARCHAR2(100) NOT NULL REFERENCES SEMESTER(SEM_NO) --학기 번호
);

--학기 정보 테이블
CREATE TABLE SEMESTER (
    SEM_NO VARCHAR2(100) PRIMARY KEY --학기번호 PK
    , YEAR NUMBER NOT NULL  --학기 년도
    , SEMESTER NUMBER NOT NULL --학기
    , SEM_NAME VARCHAR2(300) NOT NULL --학기 출력명
);

------------------------모세씨 파트--------------------------------
--학생테이블
CREATE TABLE STUDENT( 
    STU_NO VARCHAR2(100) PRIMARY KEY, --학번
    COLL_NO NUMBER NOT NULL, -- 단대번호
    MAJOR_CODE VARCHAR2(20) NOT NULL, -- 전공코드
    MINOR_CODE VARCHAR2(150) NOT NULL, -- 부전공코드
    STU_YEAR NUMBER NOT NULL, -- 학년
    STU_SEM NUMBER NOT NULL, -- 학기
    STU_STATUS VARCHAR2(50) NOT NULL, --학적상태
    MEM_NO VARCHAR2(50) NOT NULL --회원번호
    );

--학생시간표
CREATE TABLE STU_CLASS ( 
    STU_NO VARCHAR2(20) PRIMARY KEY, --학번PK
    LEC_DAY VARCHAR2(20), --날짜
    TIME_START NUMBER , --강의시작
    LEC_ROOM VARCHAR2(20) , --강의실
    LEC_NO VARCHAR2(20) NOT NULL, --강의번호
    TIME NUMBER --수업시간
    );

--학생성적확인테이블
CREATE TABLE STU_GRADE( 
    SUBJECT__ID VARCHAR2(50)PRIMARY KEY, -- 학생성적PK
    LEC_NO VARCHAR2(20) NOT NULL, --강의번호
    GRADE VARCHAR2(10) ,  --성적
    STU_NO VARCHAR2(100) NOT NULL, --학생번호
    SEM_NO NUMBER NOT NULL --학기
    );