

SELECT S.STU_NO
    , PROB_NO
FROM STUDENT S, PROBATION P
WHERE P.STU_NO = S.STU_NO;


SELECT * FROM STUDENT;
SELECT * FROM PROBATION;
SELECT * FROM LEC;
SELECT S.STU_NO
    , MAX(S.STU_YEAR) AS STU_YEAR
   , MAX(M.MEM_NO) AS MEM_NO
   , MAX(M.MEM_NAME) AS MEM_NAME
   , MAX(C.COLL_NAME) AS COLL_NAME
   , MAX(D.DEPT_NAME) AS DEPT_NAME
   , MAX(S.STU_STATUS) AS STU_STATUS
   , MAX(S.STU_SEM) AS STU_SEM
   , MAX(S.DOUBLE_NO) AS DOUBLE_NO
   , COUNT(P.STU_NO) AS PROB_CNT
   , MAX(M.MEM_EMAIL) AS MEM_EMAIL
  -- , MAX(G.GRADE) AS GRADE
  -- , MAX(G.SCORE) AS SCORE
  -- , MAX(L.LEC_NAME) AS LEC_NAME
FROM PROBATION P, STUDENT S, MEMBER M, COLLEGE C, DEPT D--, STU_GRADE G
--, LEC L
WHERE P.STU_NO(+) = S.STU_NO
AND S.MEM_NO = M.MEM_NO
AND S.COLL_NO = C.COLL_NO
AND S.DEPT_NO = D.DEPT_NO
--AND S.STU_NO = G.STU_NO(+)
--AND G.LEC_NO(+) = L.LEC_NO
GROUP BY S.STU_NO
ORDER BY S.STU_NO;

SELECT * FROM PROBATION;

SELECT * FROM LEC;
SELECT * FROM STU_GRADE;

INSERT INTO STU_GRADE (CLASS_NO, GRADE, SCORE, LEC_NO,STU_NO, SEM_NO)

SELECT 'GRADE_1',   '미등록',   0,   'LEC_1',   'STU_1',   'SEM_1' FROM DUAL
UNION ALL
SELECT 'GRADE_2',   '미등록',   0,   'LEC_2',   'STU_1',   'SEM_1' FROM DUAL;


SELECT S.STU_NO
    , MAX(C.COLL_NAME) AS COLL_NAME
    , MAX(D.DEPT_NAME) AS DEPT_NAME
    , MAX(DOUBLE_NO) AS DOUBLE_NO    
    , MAX(S.STU_YEAR) AS STU_YEAR
    , MAX(STU_SEM) AS STU_SEM
    , MAX(STU_STATUS) AS STU_STATUS
    , MAX(S.MEM_NO) AS MEM_NO
    , MAX(MEM_NAME) AS MEM_NAME
    , MAX(MEM_EMAIL) AS MEM_EMAIL
    , MAX(GRADE) AS GRADE
    , MAX(SCORE) AS SCORE
    , MAX(LEC_NAME) AS LEC_NAME
	, COUNT(P.STU_NO) AS PROB_CNT
FROM PROBATION P, STUDENT S, MEMBER M, COLLEGE C, DEPT D, STU_GRADE G, LEC L
WHERE P.STU_NO(+) = S.STU_NO
AND S.MEM_NO = M.MEM_NO
AND S.COLL_NO = C.COLL_NO
AND S.DEPT_NO = D.DEPT_NO
AND S.STU_NO = G.STU_NO(+)
AND G.LEC_NO(+) = L.LEC_NO
GROUP BY S.STU_NO;