--사원관리시스템
CREATE TABLE TEST_DEPARTMENT (
    DEPT_NUM VARCHAR2(100) PRIMARY KEY
    , DEPT_NAME VARCHAR2(100) NOT NULL
    , DEPT_LOCATION VARCHAR2(100) NOT NULL
);
SELECT * FROM TEST_DEPARTMENT;

CREATE TABLE TEST_EMP (
    EMP_NUM VARCHAR2(50) PRIMARY KEY
    , EMP_NAME VARCHAR2(100) NOT NULL
    , EMP_RANK VARCHAR2(100) NOT NULL
    , EMP_AGE NUMBER NOT NULL
    , EMP_GENDER VARCHAR2(100) NOT NULL
    , EMP_TELL VARCHAR2(100)
    , DEPT_NUM VARCHAR2(100) REFERENCES TEST_DEPARTMENT(DEPT_NUM) NOT NULL
);
INSERT INTO TEST_EMP (
    EMP_NUM
    , EMP_NAME
    , EMP_RANK
    , EMP_AGE
    , EMP_GENDER
    , EMP_TELL
    , DEPT_NUM
) VALUES (
    CONCAT('EMP', LPAD((SELECT NVL(MAX(TO_NUMBER(SUBSTR(EMP_NUM, 4))), 0) + 1 FROM TEST_EMP), 3, 0))
    , '김자바'
    , '사원'
    , 20
    , 'MALE'
    , '010'
    , 'DEPT001'
);



SELECT EMP_NUM
    , EMP_NAME
    , EMP_GENDER
    , EMP_AGE
    , EMP_TELL
    , DEPT_NAME
    , DEPT_LOCATION
FROM TEST_EMP EMP, TEST_DEPARTMENT DEPT
WHERE EMP.DEPT_NUM = DEPT.DEPT_NUM;

INSERT INTO TEST_DEPARTMENT(
    DEPT_NUM 
    , DEPT_NAME
    , DEPT_LOCATION
) VALUES (
    concat('DEPT', TO_CHAR(SELECT NVL(MAX(TO_NUMBER(DEPT_NUM)), 0) 
                    FROM TEST_DEPARTMENT))
    , '서울부2'
    , '서울'
);



INSERT INTO TEST_DEPARTMENT(
    DEPT_NUM 
    , DEPT_NAME
    , DEPT_LOCATION
) VALUES (
    CONCAT('DEPT', LPAD((SELECT NVL(MAX(TO_NUMBER(SUBSTR(DEPT_NUM, 5))), 0) + 1 FROM TEST_DEPARTMENT), 3, 0))
    , '서울부'
    , '서울'
);

SELECT * FROM TEST_DEPARTMENT;
DELETE FROM TEST_DEPARTMENT WHERE DEPT_NUM != '0';


